// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 15.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'flutter_neraca_ruang';

  static const String assets_images_dashboard_1_png = 'assets/images/dashboard_1.png';
  static const String flutter_neraca_ruang$assets_images_dashboard_1_png = 'packages/flutter_neraca_ruang/assets/images/dashboard_1.png';

  static const String assets_images_dashboard_2_png = 'assets/images/dashboard_2.png';
  static const String flutter_neraca_ruang$assets_images_dashboard_2_png = 'packages/flutter_neraca_ruang/assets/images/dashboard_2.png';

  static const String assets_images_dashboard_3_png = 'assets/images/dashboard_3.png';
  static const String flutter_neraca_ruang$assets_images_dashboard_3_png = 'packages/flutter_neraca_ruang/assets/images/dashboard_3.png';

  static const String assets_images_icon_facebook_png = 'assets/images/icon_facebook.png';
  static const String flutter_neraca_ruang$assets_images_icon_facebook_png = 'packages/flutter_neraca_ruang/assets/images/icon_facebook.png';

  static const String assets_images_icon_ig_png = 'assets/images/icon_ig.png';
  static const String flutter_neraca_ruang$assets_images_icon_ig_png = 'packages/flutter_neraca_ruang/assets/images/icon_ig.png';

  static const String assets_images_icon_kabar1_png = 'assets/images/icon_kabar1.png';
  static const String flutter_neraca_ruang$assets_images_icon_kabar1_png = 'packages/flutter_neraca_ruang/assets/images/icon_kabar1.png';

  static const String assets_images_icon_tiktok_png = 'assets/images/icon_tiktok.png';
  static const String flutter_neraca_ruang$assets_images_icon_tiktok_png = 'packages/flutter_neraca_ruang/assets/images/icon_tiktok.png';

  static const String assets_images_icon_twitter_png = 'assets/images/icon_twitter.png';
  static const String flutter_neraca_ruang$assets_images_icon_twitter_png = 'packages/flutter_neraca_ruang/assets/images/icon_twitter.png';

  static const String assets_images_icon_youtube_png = 'assets/images/icon_youtube.png';
  static const String flutter_neraca_ruang$assets_images_icon_youtube_png = 'packages/flutter_neraca_ruang/assets/images/icon_youtube.png';

  static const String assets_images_kons_png = 'assets/images/kons.png';
  static const String flutter_neraca_ruang$assets_images_kons_png = 'packages/flutter_neraca_ruang/assets/images/kons.png';

  static const String assets_images_mada_png = 'assets/images/mada.png';
  static const String flutter_neraca_ruang$assets_images_mada_png = 'packages/flutter_neraca_ruang/assets/images/mada.png';

  static const String assets_images_neraca_ruang_png = 'assets/images/neraca_ruang.png';
  static const String flutter_neraca_ruang$assets_images_neraca_ruang_png = 'packages/flutter_neraca_ruang/assets/images/neraca_ruang.png';

  static const String assets_images_nr_logo_horizontal_png = 'assets/images/nr_logo_horizontal.png';
  static const String flutter_neraca_ruang$assets_images_nr_logo_horizontal_png = 'packages/flutter_neraca_ruang/assets/images/nr_logo_horizontal.png';

  static const String assets_images_oto_png = 'assets/images/oto.png';
  static const String flutter_neraca_ruang$assets_images_oto_png = 'packages/flutter_neraca_ruang/assets/images/oto.png';

  static const String assets_images_sliding_1_png = 'assets/images/sliding_1.png';
  static const String flutter_neraca_ruang$assets_images_sliding_1_png = 'packages/flutter_neraca_ruang/assets/images/sliding_1.png';
}
