// const baseUrl = "neracaruang-api.binerapps.co.id"; // dev
const baseUrl = "api.neracaruang.com"; // prod
const loginUrl = "/api/member/login";
const registerUrl = "/api/member/register";
const dashboardList = "/api/portal/content";
const updateLikeUrl = "/api/portal/updatelike";
const updateUnlikeUrl = "/api/portal/updateunlike";
const tagsListUrl = "/api/master/gettagging";
const storageUrl = "$baseUrl/storage";
const contentUrl = "$storageUrl/content";
const thumbnailUrl = "$storageUrl/thumbnail";
const adsenseUrl = "/api/admin/adsense";
const addLike = "/api/portal/updatelike";
